apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  {{ if .Values.service }}
  type: {{ .Values.service.type | default "NodePort" | quote }}
  selector:
    app: {{ .Values.name }}
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.port | default 80 }}
      {{ if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  {{ else }}
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
    - port: 80
      targetPort: 80
  {{ end }}    